In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [13]:
b = np.ones((1,3))
c = np.random.rand(3,1)
d = np.dot(b,c)
print(c)
print(b)
print(d+1)


[[0.74029423]
 [0.27772909]
 [0.88076496]]
[[1. 1. 1.]]
[[2.89878828]]


In [17]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
B = A.sum(axis = 0)
percentage = 100 * A / B.reshape(1,4)
print(percentage)

[[ 6.66666667 11.11111111 14.28571429 16.66666667]
 [33.33333333 33.33333333 33.33333333 33.33333333]
 [60.         55.55555556 52.38095238 50.        ]]


C = np.array([[1],
             [2],
             [3],
             [4]])
print(C)             
      

In [18]:
C = np.array([[1], [2], [3], [4]]) 
print(C)

[[1]
 [2]
 [3]
 [4]]


In [19]:
print(A * C)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 